Create a custom display for the new configuration properties #42
xwikisas/integration-azure-oauth pull request #52
Opened 2024-11-13 16:35 UTC by ChiuchiuSorin

Created a new class to include additional properties to the OIDC client class and modified the listener to intercept events update and delete to be able to update the OIDC endpoints in case the tenent id is modified.
 Created a custom display for administration in AzureADClientConfigurationSheet. Administration page:

![Screenshot from 2024-11-13 18-08-09](https://github.com/user-attachments/assets/6aac6941-9dd6-49fe-be5c-5bb58b4f0227)
![Screenshot from 2024-11-13 18-08-24](https://github.com/user-attachments/assets/b19f5993-c533-44a3-92ff-fe9de2121203)
![Screenshot from 2024-11-13 18-09-43](https://github.com/user-attachments/assets/7f090ef1-2cd5-4f6a-92eb-5264146e296a)

2025-01-15 09:00 UTC, oanalavinia requested changes
Some comments
The others were discussed in a meeting :)

2025-01-15 16:44 UTC, ChiuchiuSorin commented
Made the group mapping field selectable:
![Screenshot from 2025-01-15 18-42-35](https://github.com/user-attachments/assets/b9310df8-a380-450a-8636-ea83fcb051a8)

2025-01-16 13:53 UTC, oanalavinia requested changes

2025-01-16 13:53 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +  $(document).ready(function() {
I think it would be nicer to use the 'shorter' [form](https://stackoverflow.com/questions/3528509/document-readyfunction-vs-function)

2025-01-16 13:53 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +  $(document).ready(function() {
Also, I think it would be even nicer to have methods declarations outside the `$(function() {})`, so to have better visibility on what is exactly executed when document is ready. But it might be a personal choice, it's not affecting the functionality

2025-01-16 13:53 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +    // Function to initialize and display existing properties
`.` missing at the end

2025-01-16 13:53 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +
Extra new line

2025-01-16 13:53 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +      // Hide original input, display New Entry button, and initialize properties
`.` missing

2025-01-16 13:53 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +require(['jquery',  'xwiki-l10n!entra-properties', 'xwiki-suggestGroups'],function($, l10n) {
```suggestion
require(['jquery', 'xwiki-l10n!entra-properties', 'xwiki-suggestGroups'], function($, l10n) {
```

2025-01-16 13:53 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +
```suggestion

```

2025-01-23 08:32 UTC, oanalavinia approved these changes
Looks good, thanks!

2025-01-23 08:32 UTC, oanalavinia commented on ui/src/main/resources/EntraID/Code/EntraOIDCClientConfigurationSheet.xml
> +        maybeMakeFieldSelectable(input);
Indentation

2025-01-23 09:01 UTC, merged

2025-02-11 15:42 UTC, oanalavinia commented
Hi, @ChiuchiuSorin! Can you please add on the related ticket some info about the UI changes? Similar to what you added in the description / comments above. Thanks! :)