Replace identity-oauth use with OIDC #48
xwikisas/integration-azure-oauth pull request #53
Opened 2024-11-15 16:17 UTC by ChiuchiuSorin

* created drawer header extension points to add the option to log in with XWiki
* modified configuration
* created rest endpoint to access the log in with the oidc skipped option
* created script service for Azure AD
* removed old code

2025-01-15 09:42 UTC, oanalavinia reviewed
Some comments
The other were discussed in a meeting

2025-01-16 11:51 UTC, ChiuchiuSorin commented
New drawer login options: 
![image](https://github.com/user-attachments/assets/d2b27c45-3493-4275-963b-e86221631678)
![image](https://github.com/user-attachments/assets/a634b420-c967-49fc-843a-1a2022d008d6)

2025-01-16 13:18 UTC, oanalavinia reviewed
I have a remark about the UI of the drawer buttons. I see that the already existing XWiki buttons use italic, while the new buttons do not look the same

2025-01-16 13:18 UTC, oanalavinia commented on ui/pom.xml
> +  <name>Microsoft Entra ID OpenID Connect (OIDC)</name>
I think this is the name displayed in EM. Probably better to check with @snazare about what name should we use

2025-01-16 13:18 UTC, oanalavinia commented on ui/src/main/resources/EntraID/WebHome.xml
> +    of profile information from an Microsoft Entra ID node. It uses the OIDC protocol.
A translation key could be used for this

2025-01-23 08:41 UTC, oanalavinia requested changes
Looks good overall. Just waiting for Stefana's input on the naming and also for changes / answer related to this comment https://github.com/xwikisas/integration-azure-oauth/pull/53#pullrequestreview-2556063814
Thanks!

2025-01-23 08:41 UTC, oanalavinia commented on ui/src/main/resources/EntraID/WebHome.xml
> +#set ($reference = $services.model.createDocumentReference("xwiki", ["EntraID"], "WebPreferences"))
Single quotes should be used

2025-01-23 13:40 UTC, oanalavinia commented on ui/pom.xml
> +  <name>Microsoft Entra ID SSO</name>
This naming should be applied for all modules (besides what is specific to the module)

2025-01-23 14:02 UTC, oanalavinia approved these changes

2025-01-23 14:12 UTC, merged

2025-02-11 15:43 UTC, oanalavinia commented
Hi, @ChiuchiuSorin! Can you please add on the related ticket some info about the changes applied? Similar to what you added in the description / comments above. Thanks! :)